### ISSUE TITLE
prev. speaker image sizes

### ISSUE THREAD

**Issue by xtianmcd** [delug/delug.github.io#12]
Some of the images are being warped to fit into the template. It may be best to load the ones being warped into a standard picture editing software and crop them to fit the shape desired in the website template @srs96

**Comment by zachdj** [comment]
Here's an example:
![image](https://user-images.githubusercontent.com/7102288/51862170-03b0aa00-230c-11e9-8e3c-caa731a9efbc.png)

Currently, the images are inserted using `<img>` tags.  Maybe we could replace the `<img>` tags with `<div>`s, and use the [`background-image`](https://www.w3schools.com/cssref/pr_background-image.asp) and [`background-size`](https://www.w3schools.com/cssref/css3_pr_background-size.asp) properties to display the picture with its original aspect ratio.

That might save us the work of manually editing each photo before putting it on the website.

**Comment by xtianmcd** [comment]
Agreed - unless detracts from the appearance of the page by having different image sizes. But if it looks fine, then go with it!

**Comment by srs96** [comment]
I manually formatted all the images to have almost equal width and height, and then used the style tag to set width and height to 400px. Let me know if the changes look proper.

**Comment by xtianmcd** [comment]
Looks amazing
