### ISSUE TITLE
prev. speaker pics within links to full write-ups

### ISSUE THREAD

**Issue by xtianmcd** [delug/delug.github.io#14]
the pictures within the links for some of the speakers are also morphed/squished. Not super urgent to fix, since the main pictures look good now, but should be corrected eventually

**Comment by srs96** [comment]
I fixed their aspect ratios and made them a bit smaller. Let me know if it's fine.

**Comment by xtianmcd** [comment]
Looks really nice!! Great job

**Comment by srs96** [comment]
Thanks!
