### ISSUE TITLE
Past Speakers Section

### ISSUE THREAD

**Issue by xtianmcd** [delug/delug.github.io#8]
@srs96 check out the pictures for the past speakers - they are squished, can they be reformatted to look better? Also, can some of the lengthy texts be spread over the two columns so the sections aren't so tall?

**Comment by srs96** [comment]
Okay will check it out. It was mentioned to format all pictures to 748x529 so I followed that.

**Comment by srs96** [comment]
Won't the height remain the same with columns? Should I decrease the font size instead?

**Comment by xtianmcd** [comment]
I mean the two columns that are already there; i.e., can some of the text be put on the side where the picture is, so that those sides have the picture and some of the text

**Comment by srs96** [comment]
Ah okay. I'll look into that. 

Alternatively, I was thinking, what if we only keep their name and topic with their picture? That would give a quick overview of all the speakers. And if someone is interested in a particular speaker they can click on the link to their individual page with all their info. Currently, we're displaying all the data on the past speaker page, which makes their individual pages kind of redundant and makes the past speaker page extremely long.

**Comment by srs96** [comment]
It would look something like this.

![](https://user-images.githubusercontent.com/3922528/51812041-e33a0e80-227d-11e9-8007-9b648598e055.png)

**Comment by xtianmcd** [comment]
I think that's a great idea
