### ISSUE TITLE
Previously Hosted Institutions

### ISSUE THREAD

**Issue by xtianmcd** [delug/delug.github.io#9]
Let’s add a section for “Previously Hosted Institutions” that can stay on the main page with small logos from those institutions: Georgia Tech Biomedical Engineering, Emory Neurosurgery, Emory Neuroscience, Emory Prinz lab, Gerogia Tech College of Computing, UGA Computer Science, MailChimp, UGA Instit. for AI. I’ll help you find the logos for each so you don’t have to do that by yourself

**Comment by srs96** [comment]
So just a section for them on the main page right? Or you want a separate tab?

**Comment by xtianmcd** [comment]
On the main page!

**Comment by srs96** [comment]
I'll start collecting logos and update it soon. Please forward any logos that you already have.

**Comment by xtianmcd** [comment]
I'll get on this now @srs96

**Comment by xtianmcd** [comment]
I just e-mailed you the logos @srs96

**Comment by srs96** [comment]
Added the logos and names. Let me know if any changes are required.

**Comment by xtianmcd** [comment]
Look great @srs96 ! I'm closing this issue
